import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillFacebook } from "react-icons/ai";
import Image from "next/image";
import shivy from "../public/HeadshotZoomed.png";
import code from "../public/code.png";
import consulting from "../public/earth-icon.png";
import design from "../public/design.png";
import web1 from "../public/web1.png";
import web3 from "../public/ExpenseTrackerApp.png";
import web2 from "../public/CatImage.png";
import { useState } from "react";
import Link from "next/link";

import stock1 from "../public/stockboard1.png";
import stock2 from "../public/stockboard2.png";

function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Samir Shiva Chemburkar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-300 px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="p-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons flex text-center dark:text-gray-300">
              Produced by Shiva
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl "
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-br from-cyan-600 to-red-600 text-white px-4 py-2 rounded-md ml-8"
                  href="https://docs.google.com/document/d/1bzGOXHl6JxyPuZ0EQCTVeGfrz8yydMtlbUz4lOOwMk0/edit?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center">
            <h2 className="p-3 text-5xl font-semibold text-cyan-700 md:text-6xl ">
              Shiva Chemburkar
            </h2>
            <h3 className="p-5 text-2xl md:text-3xl dark:text-gray-400">
              Front End Web Developer
            </h3>
            <p className="p-2 text-lg leading-8 md:text-xl max-w-lg mx-auto dark:text-gray-400">
              Freelancer specializing in React based projects. Has done a full
              website for the Greentree HOA based in Irvine, CA. Other react
              projects include a stock prices watchlist.
            </p>
            <div className="flex justify-center gap-10 text-5xl py-2 text-gray-600">
              <a href="https://www.facebook.com/ShivaChemburkar/">
                <AiFillFacebook />
              </a>
              <a href="https://www.linkedin.com/in/shivachemburkar/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/shivac1998">
                <AiFillGithub />
              </a>
            </div>
          </div>
          <div className="relative mx-60 overflow-hidden rounded-full w-100 h-90 mt-20 object-fill">
            <Image src={shivy} objectFit="cover" alt="" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl dark:text-gray-300">Services</h3>
            <p className="md:text-lg py-2 leading-7 dark:text-gray-300">
              Since the start of my journey as a freelance Front End Developer,
              I have completed projects with the mentorship of NiceWrk LLC. I
              have worked on collaborative projects along with individual work
              to expand my skillset as a developer. My goal is to provide{" "}
              <span className="font-semibold text-cyan-600">
                mobile application
              </span>{" "}
              and <span className="font-semibold text-cyan-600">website</span>{" "}
              building services at an{" "}
              <span className="font-semibold text-cyan-600">affordable</span>{" "}
              rate.
            </p>
            <p className="pb-8 md:text-lg py-2 leading-7 dark:text-gray-300">
              I offer a range of services which include writing the code for
              designs you may already have in mind, or starting from scratch and
              creating products you would like to have.
            </p>
          </div>
          <div className="xl:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-slate-300 dark:bg-slate-700">
              <Image src={design} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-black dark:font-medium">
                Designs
              </h3>
              <p className="md:text-xl max-w-lg mx-auto dark:text-gray-400">
                Drafting intricate designs for your approval and amendment.
              </p>
              <h4 className="py-4 font-medium text-cyan-600 ">Design tools</h4>
              <p className="text-md py-1 leading-8 dark:text-gray-400">Figma</p>
              <p className="text-md py-1 leading-8 dark:text-gray-400">
                Photoshop
              </p>
              <p className="text-md py-1 leading-8 dark:text-gray-400">
                Adobe Illustrator
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-slate-300 dark:bg-slate-700">
              <Image src={code} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-black">
                Hand-crafted beauty
              </h3>
              <p className="md:text-xl max-w-lg mx-auto dark:text-gray-400">
                Creating beautiful custom designed products that will suit your
                needs.
              </p>
              <h4 className="py-4 font-medium text-cyan-600">Coding stack</h4>
              <p className="text-md py-1 leading-8 dark:text-gray-400">
                ReactJS+NextJS+TailwindCSS
              </p>
              <p className="text-md py-1 leading-8 dark:text-gray-400">
                Git+GitHub+NodeJS
              </p>
              <p className="text-md py-1 leading-8 dark:text-gray-400">
                VS Code+Vercel+Amplify
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-slate-300 dark:bg-slate-700">
              <Image src={consulting} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-black">
                Original
              </h3>
              <p className="md:text-xl max-w-lg mx-auto dark:text-gray-400">
                Coming from a background of environmental consulting, I
                understand what it takes to meet client needs within given
                deadlines.
              </p>
              <h4 className="py-4 font-medium text-cyan-600">Soft Skills</h4>
              <p className="text-md py-1 leading-8 dark:text-gray-400">
                Flexible
              </p>
              <p className="text-md py-1 leading-8 dark:text-gray-400">
                Effective communicator
              </p>
              <p className="text-md py-1 leading-8 dark:text-gray-400">
                Strong work-ethic
              </p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-400">Portfolio</h3>
            <p className="dark:text-gray-400">
              Screenshots of deployed projects.
            </p>
          </div>

          <div className="flex flex-col gap-10 xl:col-2 lg:pb-5 pt-10 lg:flex-row  ">
            <div className="basis-1/3 flex-1">
              <h3 className="pb-5 text-xl xl:text-2xl dark:text-gray-400">
                Greentree Homes
              </h3>
              <Link href="https://www.greentreeirvinehomes.com/">
                <Image
                  src={web1}
                  className="rounded-lg object-contain cursor-pointer"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  alt=""
                />
              </Link>
            </div>
            {/* <div className="basis-1/3 flex-1">
              <h3 className="pb-5 text-xl dark:text-gray-400">
                Expense Tracker
              </h3>
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"85%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </div> */}
            <div className="basis-1/3 flex-1">
              <h3 className="pb-5 text-xl xl:text-2xl dark:text-gray-400">
                Stock Dashboard
              </h3>
              <Link href="https://master.d4gla9n1k7647.amplifyapp.com/">
                <Image
                  src={stock1}
                  className="rounded-lg object-scale-down cursor-pointer"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  alt=""
                />
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

export default Home;
